apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: brtc-kotlin-sample-application-location
  description: Links to additional entities in the brtc-kotlin-sample-application repository.
  annotations:
    github.com/project-slug: Bandwidth/brtc-kotlin-sample-application
spec:
  targets:
    - ./component.yaml
    # - add more components using relative filepaths here
    # - you may also rename/move the original component.yaml file
