apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: kotlin-brtc-sample-application
  description: Sample application that implements the BRTC Kotlin SDK
  annotations:
    github.com/project-slug: Bandwidth-Samples/kotlin-brtc-sample-application
  organization: BW
  costCenter: 
  platformType: AWS
  buildPlatform: GitHub Actions
spec:
  type: Service
  owner: github/band-programmable-voice
  lifecycle: Prototype
  
